image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

stages:
  - format

before_script:
  - npm install

run_prettier:
  stage: format
  script:
    - npm run prettier:diff

run_lint:
  stage: format
  script:
    - npm run lint
