image: node:latest

stages:
  - format

before_script:
  - npm install

run_prettier:
  stage: format
  script:
    - npm install -g prettier
    - prettier --list-different 'src/**/*.{js,json}' '*.js'

run_lint:
  stage: format
  script:
    - npm install -g eslint babel-eslint eslint-config-prettier eslint-plugin-babel eslint-plugin-react eslint-plugin-react-native
    - eslint --report-unused-disable-directives --max-warnings=0 --cache src/ *.js
