# this config tree assumes order, even for yaml hashes!
measure_height:
  params:
    create:
      tower_2: []
    modify:
      tower_2: { position: [65vw, 0] }
    event_handling:
      target: tower_2
      touch_reveals_button: [submit, delete]
    misc:
      remove_on_exit: [button_submit, button_delete]
      config_iteration: 7
      # config_iteration: 1
      num_stars: 3
  animal_height:
    params:
      generate: { tile_1_name: [pick_animal_name] }
      create:
        tile_1: { name: tile_1_name }
      modify:
        tile_1: { position: [right 40vw, 0] }
      event_handling:
        comparison_source: tile_1
        correctness: approx_height
    level_4:
      params:
        create:
          keypad_kind: 'buildTower'
        modify:
          tower_2:
            tower_style: { opacity: 1 }
  to_handle:
    params:
      generate: { door_1_name: [pick_from_range, .1, 1.8, .1] }
      create:
        door_1: { name: [door_1_name] }
      modify:
        door_1: { position: [right 60vw, 0] }
      event_handling: { comparison_source: door_1, correctness: same_height }
    level_4:
      params:
        create:
          keypad_kind: 'buildTower'
        modify:
          tower_2:
            tower_style: { opacity: 1 }
