# this config tree assumes order, even for yaml hashes!
measure_height:
  params:
    create:
      tower_2: []
    modify:
      tower_2: { position: [65vw, 0] }
    event_handling:
      target: tower_2
      touch_reveals_button: [submit, delete]
    misc:
      remove_on_exit: [button_submit, button_delete]
      config_iteration: 7
      # config_iteration: 1
      num_stars: 3
  animal_height:
    params:
      generate: { tile_1_name: [pick_animal_name] }
      create:
        tile_1: { name: tile_1_name }
      modify:
        tile_1: { position: [right 40vw, 0] }
      event_handling:
        comparison_source: tile_1
        correctness: approx_height
    level_3:
      params:
        create:
<<<<<<< HEAD
          keypad_kind: 'buildTower'
        modify:
          tower_2:
            tower_style: { opacity: 1 }
  to_handle:
=======
          big_paren: remove
          big_op: remove
        event_handling:
          touch_reveals_button: [delete]
    level_1:

subitize:
  params:
    generate:
      num_animals: [pick_from_range, 0.3, 3.9, 0.1]
      option_value_delta: 0.2
      option_value_seed: num_animals
      restriction_3: option > 0
      restriction_4: option < 4
      m1: num_animals
    create:
      tower_1: { name: m1 }
      tower_2: { name: 1 }
    modify:
      tower_1:
        position: [15, 0]
        misc:
          hide_tower_number: true
          backgroundColor: 'black'
      tower_2:
        position: [0, 0]
        misc:
          is_option: true
          option_offset: 220
          option_width: 110
          backgroundColor: 'purple'
    event_handling:
      correctness: identical
      target: tower_2
      arg_1: tower_1
      comparison_source: tower_1
    misc:
      new_scale_factor: 200
      config_iteration: 5
  level_1:
  disappearing:
>>>>>>> 69f1f8995a3cd47a9d37b0d373c4a222248a4baf
    params:
      generate: { door_1_name: [pick_from_range, .1, 1.8, .1] }
      create:
        door_1: { name: [door_1_name] }
      modify:
        door_1: { position: [right 60vw, 0] }
      event_handling: { comparison_source: door_1, correctness: same_height }
    level_3:
      params:
        create:
          keypad_kind: 'buildTower'
        modify:
          tower_2:
            tower_style: { opacity: 1 }
