# this config tree assumes order, even for yaml hashes!
addition_mix_and_match:
  params:
    generate: # { tower_1_name: [pick_from_range, .1, 3.8, .1] }
      tower_1_height: [pick_from_range, 0.3, 2, 0.1]
      tower_2_height: [pick_from_range, 0.3, 3, 0.1]
      mixed_tower_height: tower_1_height + tower_2_height
      restriction_upper: mixed_tower_height < 3.9
    create:
      keypad_kind: 'buildTower'
      big_paren: true
      big_op: +
      tower_2_shadow: { name: tower_2_height }
      tower_1_shadow: { name: tower_1_height }
      tower_2: { name: tower_2_height }
      tower_1: { name: tower_1_height }
      tower_mixed: []
      tower_result: []
      tower_4: { name: mixed_tower_height }
    modify:
      big_paren:
        position: [20, 0]
        style: { width: 330 }
      big_op:
        position: [120, 0]
      tower_1:
        position: [15, 0]
        tower_style: {opacity: 0.2}
        misc:
          hide_tower_number: true
          backgroundColor: 'blue'
      tower_1_shadow:
        position: [15, 0]
        misc:
          backgroundColor: 'blue'
      tower_2:
        position: [230, 0]
        tower_style: {opacity: 0.2}
        misc:
          hide_tower_number: true
          backgroundColor: 'red'
      tower_2_shadow:
        position: [230, 0]
        misc:
          backgroundColor: 'red'
      tower_mixed:
        position: [340, 0]
        tower_style: {opacity: 0}
        misc:
          hide_tower_number: true
      tower_result:
        position: [380, 0]
        # tower_style: {opacity: 0}
        misc:
          backgroundColor: 'black'
      tower_4:
        position: [0, 0]
        style: {opacity: 0}
    event_handling:
      correctness: identical
      touch_reveals_button: [submit, delete]
      no_split_fiver: true
      minimum_split_size: -1
      target: tower_result
      comparison_source: tower_4
    misc:
      num_stars: 2
      remove_on_exit: [button_submit, button_delete]
      config_iteration: 4
      trigger_blocks_moving_to_result: 0
  level_1:
    params:
      misc:
        jmp: [addition_mix_and_match, level_1]
  disappearing:
    params:
      create:
        button_start:
      misc:
        freeze_display: true
        # jmp: [addition_mix_and_match, level_1]
      modify:
        tower_1:
          style: { opacity: 0 }
        tower_1_shadow:
          style: { opacity: 0 }
        tower_2:
          style: { opacity: 0 }
        tower_2_shadow:
          style: { opacity: 0 }
      delay:
        modify:
            tower_1:
              style: { opacity: 1 }
              anim_info: { opacity: [1, 0], delay: 0, duration: 2000 }
            tower_2:
              style: { opacity: 1 }
              anim_info: { opacity: [1, 0], delay: 0, duration: 2000 }
            tower_1_shadow:
              style: { opacity: 1 }
            tower_2_shadow:
              style: { opacity: 1 }
    level_2:

open_build:
  params:
    generate:
      mean_name: [fixed, []]
    create:
      keypad_kind: 'buildTower'
      tower_result: []
    modify:
      tower_result:
        position: [42vw, 0]
        misc:
          backgroundColor: 'black'
    event_handling:
      target: tower_result
      touch_reveals_button: [delete]

subitize:
  params:
    generate:
      num_animals: [pick_from_range, 0.3, 3.9, 0.1]
      option_value_delta: 0.2
      option_value_seed: num_animals
      restriction_3: option > 0
      restriction_4: option < 4
      m1: num_animals
    create:
      tower_1: { name: m1 }
      tower_2: { name: 1 }
    modify:
      tower_1:
        position: [15, 0]
        misc:
          hide_tower_number: true
          backgroundColor: 'black'
      tower_2:
        position: [0, 0]
        misc:
          is_option: true
          option_offset: 220
          option_width: 110
          backgroundColor: 'purple'
    event_handling:
      correctness: identical
      target: tower_2
      arg_1: tower_1
      comparison_source: tower_1
      disappearing_object: tower_1
    misc:
      new_scale_factor: 200
      config_iteration: 5
  level_1:
  disappearing:
    params:
      create:
        button_start:
      modify:
        tower_1:
          anim_info: null
          style: { opacity: 0 }
        tower_2:
          style: { opacity: 0 }
      misc:
        freeze_display: true
      delay:
        modify:
          tower_1:
            style: { opacity: 1 }
            anim_info: { opacity: [1, 0], delay: 0, duration: 1000 }
          tower_2:
            style: { opacity: 1 }
    level_2:
      params:
        misc:
          jmp: [subitize, disappearing, level_2]
    level_3:
      params:
        modify:
          tower_2:
            tower_style: { opacity: 0 }
        delay:
          modify:
            tower_1:
              style: { opacity: 1 }
              anim_info: { opacity: [1, 0], delay: 0, duration: 2000 }

in_between:
  params:
    create:
      button_next:

measure_height_animals:
  params:
    generate: { tile_1_name: [pick_animal_name] }
    create:
      tower_2: []
      tile_1: { name: tile_1_name }
    modify:
      tower_2: { position: [65vw, 0] }
      tile_1: { position: [right 40vw, 0] }
    event_handling:
      target: tower_2
      touch_reveals_button: [submit, delete]
      comparison_source: tile_1
      correctness: approx_height
    misc:
      remove_on_exit: [button_submit, button_delete]
      config_iteration: 7
      num_stars: 3
  level_1:
    params:
      create:
        keypad_kind: 'buildTower'
      modify:
        tower_2:
          tower_style: { opacity: 1 }
          misc:
            backgroundColor: 'black'
      misc:
        jmp: [measure_height_animals, level_1]

redbluequiz:
  params:
    generate:
      m1: [pick_from_range, 0.3, 2.1, 0.1]
      m2: [pick_from_range, 0.3, 2.1, 0.1]
      mean_name: m1 + m2
      option_value_delta: 0.2
      option_value_seed: mean_name
      restriction_3: option > 0
      restriction_4: option < 4
    create:
      tower_2: { name: m2 }
      tower_1: { name: m1 }
      tower_frame_2: { name: 1 }
      tower_mixed: []
    modify:
      tower_frame_2:
        position: [0, 0]
        misc:
          is_option: true
          option_offset: 220
          option_width: 110
          backgroundColor: 'black'
      tower_1:
        position: [0, 0]
        misc:
          backgroundColor: 'blue'
          hide_tower_number: true
      tower_2:
        position: [0, 0]
        misc:
          backgroundColor: 'red'
          hide_tower_number: true
      tower_mixed:
        position: [15, 0]
        tower_style: {opacity: 0}
        misc:
          hide_tower_number: true

    event_handling:
      correctness: identical
      target: tower_frame_2
      arg_1: tower_1
    misc:
      new_scale_factor: 200
      config_iteration: 5
      num_stars: 3
      trigger_blocks_moving_to_result: 0
  level_1:
    params:
      misc:
        jmp: [redbluequiz, level_1]
  disappearing:
    params:
      create:
        button_start:
      modify:
        tower_1:
          anim_info: null
          style: { opacity: 0 }
        tower_2:
          style: { opacity: 0 }
      misc:
        freeze_display: true
      delay:
        modify:
            tower_1:
              style: { opacity: 1 }
              anim_info: { opacity: [1, 0], delay: 0, duration: 2000 }
            tower_2:
              style: { opacity: 1 }
              anim_info: { opacity: [1, 0], delay: 0, duration: 2000 }
