export const NUM_CREATE = 'NUM_CREATE';
export const NUM_SET_NAME = 'NUM_SET_NAME';
export const NUM_SET_POSITION = 'NUM_SET_POSITION';
export const NUM_SET_OPACITY = 'NUM_SET_OPACITY';
export const NUM_SET_BLOCK_OPACITY = 'NUM_SET_BLOCK_OPACITY';
export const SET_SCALE_FACTOR = 'SET_SCALE_FACTOR';
export const SET_KEYPAD_KIND = 'SET_KEYPAD_KIND';
export const SET_BUTTON_HIGHLIGHT = 'SET_BUTTON_HIGHLIGHT';