# this config tree assumes order, even for yaml hashes!
params:
  modify:
    expr_1: {left: 5, arg_spacing: 20, res_spacing: 30}
    button_submit: { position: [5, 200] }
  # starting_config_path: ['all_done']
  # starting_config_path: ['in_between']
  # starting_config_path: ['multiply_height', 'animal_target', 'touch_image']
  # starting_config_path: ['multiply_height', 'animal_target', 'move_handle']
  # starting_config_path: ['multiply_height', 'door_target', 'move_portal_handle_to_shadow']
  starting_config_path: ['multiply_height', 'door_target', 'move_portal_handle_to_shadow', 'level_2', 'level_2a']
  # starting_config_path: ['multiply_height', 'door_target', 'general_case', 'level_1']
  # starting_config_path: ['measure_height', 'animal_height_subitize', 'level_1']
  # starting_config_path: ['measure_height', 'copy_tower_subitize', 'level_1']
  # starting_config_path: ['measure_height', 'animal_height', 'level_1']
  # starting_config_path: ['measure_height', 'copy_tower', 'level_1']
measure_height:
  params:
    create:
      keypad_kind: 'buildTower'
      tower_2: []
      button_submit:
    event_handling: { target: tower_2 }
    modify:
      tower_2: { position: [65vw, 0] }
    misc: {config_iteration: 1, num_stars: 3}
  copy_tower:
    params:
      generate: { tower_1_name: [pick_from_range, .1, 1.8, .1] }
      create:
        tower_1: { name: tower_1_name }
      modify:
        tower_1: { position: [5, 0],
          width: 60vw, overflow: 'hidden'
        }
      event_handling: { comparison_source: tower_1, correctness: identical }
    level_1:
    level_2:
  animal_height:
    params:
      generate: { tile_1_name: [pick_animal_name] }
      create:
        tile_1: { name: tile_1_name }
      modify:
        tile_1: { position: [right 40vw, 0] }
      event_handling: { comparison_source: tile_1, correctness: same_height }
    level_1:
    level_2:
  copy_tower_subitize:
    params:
      generate: { tower_1_name: [pick_from_range, .1, 1.8, .1] }
      create:
        tower_1: { name: tower_1_name }
      modify:
        tower_1: { position: [5, 0],
          width: 60vw, overflow: 'hidden',
          appear_after: 2000,
          fade_anim: { start: 2500, duration: 500 }
        }
      event_handling: { comparison_source: tower_1, correctness: identical }
  animal_height_subitize:
    params:
      generate: { tile_1_name: [pick_animal_name] }
      create:
        tile_1: { name: tile_1_name }
      modify:
        tile_1: { position: [right 40vw, 0],
          appear_after: 2000,
          fade_anim: { start: 2500, duration: 500 }
        }
      event_handling: { comparison_source: tile_1, correctness: same_height }
multiply_height:
  params:
    generate: { portal_1_name: [uniform, .1, 1.], 
                door_3_name: [uniform, .1, 1.], }
    create:
      door_3: { name: [door_3_name] }
      # door_3: [0.29]
      # portal_1: { name: [1] }
      portal_1: [.9]
      # tower_1: { name: [.5, .3] }
      # button_submit:
    modify:
      door_3: { position: [320, 0] }
      portal_1: { position: [0, 0], misc: {handle_blink: 0} }
      # tower_1: { position: [50vw, 0] }
    event_handling: 
      arg_1: portal_1
      result: door_3
      correctness: near_height
      top_right_text: average_error
      star_policy: extraLoose 
      slide_portal: true
    misc: { config_iteration: 1, num_stars: 3 }
  animal_target:
    params:
      generate: { tile_2_name: [pick_animal_name],
                  restriction_1: tile_2_name < 1.0,
                  restriction_2: door_3_name < tile_2_name }
      create:
        # tile_2: { name: "puppy" }
        tile_2: { name: tile_2_name }
      modify:
        tile_2: { position: [right 180, 0] }
      event_handling: { arg_2: tile_2, target: portal_1 }
    touch_image:
      params:
        modify:
          portal_1: { position: [0, 0], misc: {handle_blink: null} }
          tile_2: { misc: {blink: .5} }
        event_handling: { move: touch_image }
    move_handle:
      params:
        event_handling: { move: move_handle }
  door_target:
    params:
      generate: { door_2_name: [uniform, .1, 1.],
                  door_3_name: portal_1_name * door_2_name,
                  restriction_2: door_3_name < door_2_name }
      create:
        door_2: { name: [door_2_name] }
        # door_2: [.5]
      modify:
        door_2: { position: [220, 0] }
      event_handling: { arg_2: door_2, move: move_handle }
    move_portal_handle_to_match:
      params:
        event_handling: { target: portal_1 }
    move_portal_handle_to_shadow:
      params:
        create:
          portal_1: { name: [1, portal_1_name] }
          button_submit: remove
        modify:
          door_3: { style: {opacity: 0} }
        event_handling: 
          target: portal_1
          star_policy: strict
      level_1:
      level_2:
        params:
          misc: 
            config_iteration: null
        level_2a:
          params:
            misc: 
              skip_submit: true
              skip_in_between: true
        level_2b:
          params:
            create:
              portal_1: { name:  [portal_1_name, portal_1_name] }
            modify:
              portal_1: { misc: {handle_blink: null} }
              door_3: { style: {opacity: 1}, misc: {blink: 0, handle_opacity: 0} }
            event_handling: 
              target: door_3
            misc: 
              goto_config: [2, ['multiply_height', 'door_target',
                'move_portal_handle_to_shadow', 'level_2', 'level_2a']]
    general_case:
      params:
        generate:
          door_3_name: [uniform, .1, 1.]
        create:
          portal_1: { name:  [1, portal_1_name] }
          err_box:
        event_handling: 
          target: door_3
          show_camel: true
          slide_portal: false
      level_1:
        params:
          misc: 
            #goto_config: [2, ['multiply_height', 'door_target', 'move_handle']]
      # level_2:
      # level_3:
all_done:
  params:
    create:
      center_text:  That's all for today!
# bar_addition:
# - params:
#   - generator: {random1: uniform, random2: uniform, sum_in_range: [.1,1]}
#   - event_handling: {down: jump_if_far, move: by_delta, submit: error_animation }
#   - misc: {num_exercises: 4}
#   - create:
#     - expr1:
#       - params: {op: +, left: 35}
#       - bar1: {value: random1}
#       - bar2: {value: random2}
#       - door1:
#         - params: {-locked, +knob_hidden, +is_target}
#     - button_submit: []
#   - modify: []
# - replicate_close_tile_height:
#   - params: {}
# - replicate_far_tile_height: []
# - replicate_far_tile_height:
#   - params: {maxNumExercises: 3}
#   - ex1:
#     - params: {+size11x17, +justStandardize}
#   - ex2:
#     - params: {+size8p5x11, +rebuildTower, +removeBorders}
# choose_tower_name:
# pack_unpack:
# standardize:
# estimate_sums:
# single_size_addition:
# multi_size_addition_1:
# multi_size_addition_2:
# decimal_frame:
# decimal_number:
# suuji_multiplication:
# estimating_products:
# multi_digit_addition:
# multi_digit_subtraction:
# shrinking_a_tower:
# multi_size_multiplication:
# decimal_to_shrink:
# multi_digit_multiplication:
in_between:
  params:
    create:
      button_next: